export const NAVIGATION = {
  APP_NAVIGATOR: "AppNavi",
  LOGIN: "Login",
  WELCOME: "Welcome",
  DRAWER: "MyDrawer",
  REGISTER: "Register",
  MATCH_DETAILS: "MatchDetails",
  PROFILE: "ProfileScreen",
  ADD_PLAYER: "ADD_PLAYER",
  ADD_TEAM: "ADD_TEAM",
  ADMIN_HOME: "ADMIN_HOME",
  CREATE_TOURNAMENT: "CREATE_TOURNAMENT",
  ALL_USERS: "ALL_USERS",
  ALL_PLAYERS: "ALL_PLAYERS",
  ALL_TEAMS: "ALL_TEAMS",
  ALL_TOURNAMENTS: "ALL_TOURNAMENTS",
  POINTS_SYSTEM: "POINTS_SYSTEM",
  WINNING_POINTS: "WINNING_POINTS",
  prod: {
    url: `http://baapi.inland.in/V1/BAAPI.svc/BAAPI`, // prod
  },
};
